# January 13 2021 – Getting a working GPT2 model running on Raspberry Pi 4 with Python
# Details of my setup: Raspberry Pi OS on Raspberry Pi 4 (4GB RAM) + 128GB Samsung EVO+ MicroSD card
# This is under the assumption you are NOT SSH/remote into Raspberry Pi OS

# 1) Open terminal window on Raspberry Pi OS

# 2) You may want to update Python and IDLE: 
sudo apt update
# (As of today I have Python 3.7.3)

sudo apt install python3 idle3
# (Updating IDLE is optional since everything is happening inside terminal)

# 3) Install/update pip:
sudo apt install python3-pip

# 4) Install/update virtualenv:
sudo apt install virtualenv python3-virtualenv –y

# 5) Create a virtual environment (env) called 'testpip' (you can name it whatever):
virtualenv -p /usr/bin/python3 testpip
source testpip/bin/activate

# 6) Your prompt should go from "pi@raspberrypi" --> "(testpip) pi@raspberrypi"
# (Indicates you are inside the virtualenv 'testpip' that you created)

# 7) Inside the virtualenv 'testpip' we install the various packages and libraries to use within the 'testpip' virtualenv (only)

# 8) For instance if you want scipy (which will also install numpy):
pip install scipy

# 9) The following commands install Tensorflow and various other dependencies to make it run:
sudo apt-get install -y libhdf5-dev libc-ares-dev libeigen3-dev
python3 -m pip install keras_applications==1.0.8 --no-deps
python3 -m pip install keras_preprocessing==1.1.0 --no-deps
python3 -m pip install h5py==2.9.0
sudo apt-get install -y openmpi-bin libopenmpi-dev
sudo apt-get install -y libatlas-base-dev
python3 -m pip install -U six wheel mock

# 10) These steps are specific to getting Tensorflow 1.13.1
# (which works with gpt2client, unsure if any slightly newer versions of Tensorflow will work.
# The gpt2client package states that 2.0 and newer don’t.)

# a) Go to this website: https://www.piwheels.org/project/tensorflow/#install
# b) Scroll down to find the 1.13.1 version of Tensorflow and click the blue box
# c) Copy the link for the "tensorflow-1.13.1-cp37-none-linux_armv7l.whl" file

# d) In terminal type: 
wget (insert copied link here)

# e) Uninstall previous versions of Tensorflow (if you have any):
python3 -m pip uninstall tensorflow

# f) Since we are in a virtual environment, type:
pip install tensorflow==1.13.1

# 11) Close terminal window and then open a new terminal window
cd testpip 
# (or whatever you named your virtualenv that we created earlier)

source bin/activate
# prompt should change "pi@raspberrypi" --> "(testpip) pi@raspberrypi"

# 12) Let's go through some checks:
# a) Type and enter: 
python3
# (Displays various info and opens Python interpreter within Terminal)

# b) The previous step will also change your prompt to become ">>>"
# c) Type and enter:
import tensorflow 
# (There will be lots of warnings and stuff but another ">>>" should show up)

# d) double check tensorflow version with:
tensorflow.__version__
# You should see: ‘1.13.1’
# (Note that there are 2 "_" in front and after the word 'version')

# 12) a) Now exit the Python interpreter with:
exit()

# b) In 'testpip' virtualenv, install the GPT2Client:
pip install gpt2-client

# c) Once done downloading and installing (hopefully successfully), type:
python3

# 13) a) Now back inside the Python interpreter we will re-check everything:
import tensorflow
tensorflow.__version__
# (_ _version_ _ without the spaces between each "_") --> again should display: '1.13.1'

# b) Type:
from gpt2_client import GPT2Client

# c) Then type:
gpt2 = GPT2Client('345M')
# (The less ram you have you may want to use a smaller model; I have 4gb ram)
# (Other model options: '117M', '774M' or the largest at '1558M')

# Use the following line of code the first time you are using each of the model options:
gpt2.load_model(force_download=True)
# This downloads the different model sizes the first time that you use each of the sizes.
# Use this line to re-download the same model size over your existing download of that model.

# Once the '345M' model is downloaded, the next time you use the 345M model you type:
gpt2.load_model(force_download=False)

# d) Now type:
gpt2.generate(interactive=True)
# (Asks the user for a prompt but it takes some time before it asks for the prompt)
# This is the prompt I used. It’s the same prompt used in the reddit post that inspired me (link below) to get this whole process working and written down:

# "I've worked hard to create this disk image for folks who want to experiment so they can get a working copy of GPT-2.
# Now I hope to see some inspiring results, and I hope you'll all share"

# e) The sample generated by GPT2 is going to take a while so: take a nap or do a quick work out
# (Warning: pressing any keys on your keyboard might interrupt the process and you will have to re-enter your prompt and start waiting again)

# f) This is the sample text generated by the '345M' GPT2 model using the prompt above:

# "Scottish Parliament sits in Edinburgh and oversees EU affairs.
# But the UK Government in Edinburgh, where Scots have their heads held high and the Scottish Government is almost entirely in London (the Scottish Parliament's new leader has been sacked from Edinburgh City Council just over a week ago), can not force the Scottish Government to go further and join its "big boys" in Brussels – such as the EU and China – who, by contrast, are far more constrained by Westminster.
# Despite the fact that Scotland has voted overwhelmingly to remain in the EU, and despite it enjoying much the same tax rates as other EU countries – including those in England and Wales, and also France and Italy – the UK Government is determined to restrict other countries' access to Scottish markets and access to a trade deal.
# What are the options?
# The Scottish Government says that this means they have no choice but to seek agreement with the EU on many of its matters, such as migration, environmental policy, trade and investment – the same areas where Brussels would be unlikely to compromise on Scotland's sovereignty and the protection of our land and water.
# This is because the British Government in Edinburgh, both Labour and Tory, would prefer an accord with the EU rather than to be forced to negotiate on these matters with Scotland.
# However, the Scottish Government must also accept the current EU agreement on free movement of people – which would mean that Scottish citizens could be forced to work EU citizens from their country of birth, for example, rather than leaving them free to move into the UK from as many as 60 countries, most of them EU countries. Scotland would also need to accept that any future British-only trade deals would take into account EU customs and the rules on free movement of people.
# This can only be a good situation for Scotland if Scotland, which enjoys a relatively low average immigration to the UK from Scotland – about 2,500 a year, compared with EU figures of about 20,000 – is excluded from the current free movement agreement. Even in the rare circumstances where Scottish citizens were able to immigrate from other EU countries, they are still not free to do so – as this is not available to citizens living in the UK.
# Some have raised how this leaves Scotland without a viable negotiating position for the future. However, this is unlikely to change without a major change in the UK Government's negotiating approach.
# How are we going to prevent it happening?
# The Scottish Government have been clear for some time that there is no need to leave the EU – in fact Scotland will retain the free movement of people agreement because it has been the UK Government's position for many years that it would be preferable.
# However, the current Brexit agreement cannot legally be altered unilaterally in the British Parliament or House of Commons even without the UK Government first agreeing changes in the way its legislation deals with Scotland.
# The UK Government is also not willing to have an extra vote in the House of Commons (for example in the recent reshuffle by the Speaker) to change the free movement of people agreement between the UK and the EU.
# The SNP and the Scottish Government are not willing to allow this to happen. Scottish people strongly support staying in the EU and want to ensure that any trade deal that comes out of the UK and the EU would give equal value to UK and EU citizens within the same framework.
# The EU is prepared to negotiate these free movement issues. They have agreed they will continue to have a trade deal, which is currently being developed, with Scotland. An agreement on trade and investment with Scotland, which could be in the range of the FTA between the UK and some of the EU's most important industries, would give Scots jobs in Scotland that they haven't had for some time.
# But there's been a lack of agreement on how to get around Parliament's ability to change the EU agreement.
# The Scottish Government, which has made clear that all EU citizens must register their Scottish domicile when travelling in the UK to apply for visas or for British or Irish citizens to work in Ireland or the UK.
# But this has to be negotiated separately with Parliament and the British Government in the British parliament in the future. This would require a major compromise of Parliament's power.
# What is a major compromise?
# Scotland has said that in the UK, it would be impossible for any legislation that affects immigration policy (such as changes to the immigration rules) to be passed by Parliament without it first first securing the backing of the European Commission (which is in charge). Therefore, all other EU government ministers and the British government would need to become "partners" in any legislation.
# The EU also has a "strategic partnership" with the UK which includes issues relating to migration that the government doesn't want to touch."

# g) The result I received above is based on no training or settings for the GPT2 model. Just gave it a prompt and let it run for 20-30 minutes.
# The very bottom link I referred to has more information on working with the GPT2 model via the Client wrapper like: how many pieces of text to create.

# 14) Final Notes: a) To close out of the 'testpip' virtualenv use: 
deactivate

# b) To delete 'testpip' virtualenv and everything in it use:
rm -rf testpip/

# ==============================================================================
# This is an alternate step 10 if you want a newer version of Tensorflow. I couldn't get it work with gpt2client and they say it doesn't as well.
# This would be good for if you wanted to do stuff other than GPT2 work.

# 10) These steps are specific to Tensorflow 2.0.0; go to this site:
# a) Go to this website: https://github.com/lhelontra/tensorflow-on-arm/releases

# b) Scroll down to the "Tensorflow - 2.0" heading and find the "Asset" called: "tensorflow-2.0.0-cp37-none-linux_armv7l.whl"

# c) It should appear as a link or download file but just copy the link address

# d) Then back in the terminal window where we left off, type:
wget (paste the copied link address here)

# e) Uninstall previous versions of Tensorflow (if you have any):
python3 -m pip uninstall tensorflow

# f) Finally install Tensorflow 2.0 from the file link we copied earlier:
python3 -m pip install tensorflow-2.0.0-cp37-none-linux_armv7l.whl
# ==============================================================================

# Inspiration for this came from this post on reddit:
# https://www.reddit.com/r/raspberry_pi/comments/ktx3pc/anyone_interested_in_an_image_for_the_pi_4_8_gig/

# Resources used to find these steps come from a mix of the following:
# https://projects.raspberrypi.org/en/projects/generic-python-install-python3#linux
# https://www.piwheels.org/
# https://www.youtube.com/watch?v=GNRg2P8Vqqs&list=WL&index=4
# https://pypi.org/project/gpt2-client/
